import packageImg from "@/app/assets/package1.png"
export const packagesData = [
  {
    id: 1,
    name: "Starter Package",
    packageImg: packageImg,
    lessons: 5,
    duration: "5 Hours",
    durationNum: 5,
    price: 299,
    originalPrice: 349,
    description: "Perfect for beginners starting their driving journey.",
    features: [
      "5 driving lessons",
      "Theory material",
      "Progress tracking",
      "Beginner friendly",
    ],
    popular: false,
    savings: 50,
    category: "beginner",
  },
  {
    id: 2,
    name: "Standard Package",
    packageImg: packageImg,
    lessons: 10,
    duration: "10 Hours",
    durationNum: 10,
    price: 549,
    originalPrice: 649,
    description: "Build confidence with structured lessons.",
    features: [
      "10 driving lessons",
      "Highway training",
      "Night driving",
      "Free mock test",
    ],
    popular: true,
    savings: 100,
    category: "intermediate",
  },
  {
    id: 3,
    name: "Premium Package",
    packageImg: packageImg,
    lessons: 15,
    duration: "15 Hours",
    durationNum: 15,
    price: 799,
    originalPrice: 949,
    description: "Advanced training with mock test preparation.",
    features: [
      "15 driving lessons",
      "Test routes practice",
      "Priority scheduling",
      "Guaranteed test slot",
    ],
    popular: false,
    savings: 150,
    category: "advanced",
  },
  {
    id: 4,
    name: "Test Ready Package",
    packageImg: packageImg,
    lessons: 3,
    duration: "3 Hours",
    durationNum: 3,
    price: 199,
    originalPrice: 249,
    description: "Final preparation before your driving test.",
    features: [
      "3 intensive lessons",
      "Test simulation",
      "Examiner tips",
      "Car for test day",
    ],
    popular: false,
    savings: 50,
    category: "test",
  },
  {
    id: 5,
    name: "Refresher Package",
    packageImg: packageImg,
    lessons: 4,
    duration: "4 Hours",
    durationNum: 4,
    price: 249,
    originalPrice: 299,
    description: "Ideal for returning or nervous drivers.",
    features: [
      "4 refresher lessons",
      "Confidence building",
      "Road safety update",
      "Flexible timing",
    ],
    popular: false,
    savings: 50,
    category: "refresher",
  },
  {
    id: 6,
    name: "Intensive Course",
    packageImg: packageImg,
    lessons: 20,
    duration: "20 Hours",
    durationNum: 20,
    price: 999,
    originalPrice: 1199,
    description: "Complete driver training in shortest time.",
    features: [
      "20 comprehensive lessons",
      "All road types",
      "Emergency handling",
      "Certificate of completion",
    ],
    popular: true,
    savings: 200,
    category: "intensive",
  },
  {
    id: 7,
    name: "Weekend Warrior",
    packageImg: packageImg,
    lessons: 8,
    duration: "8 Hours",
    durationNum: 8,
    price: 449,
    originalPrice: 529,
    description: "Weekend-only lessons for busy schedules.",
    features: [
      "8 weekend lessons",
      "Saturday/Sunday slots",
      "Pickup service",
      "Progress reports",
    ],
    popular: false,
    savings: 80,
    category: "weekend",
  },
  {
    id: 8,
    name: "Express Pass",
    packageImg: packageImg,
    lessons: 12,
    duration: "12 Hours",
    durationNum: 12,
    price: 699,
    originalPrice: 799,
    description: "Fast-track to your driving test.",
    features: [
      "12 focused lessons",
      "Test booking assistance",
      "Extra practice hours",
      "Discount on retest",
    ],
    popular: true,
    savings: 100,
    category: "fast-track",
  },
];