import packageImg from "@/app/assets/package1.png";
export const packagesData = [
  {
    name: "Disability Test Package with 1 hour lesson",
    packageThumbline: "https://i.ibb.co/Xf18PmCP/package1.png",
    lessons: 1,
    duration: "1 Hours",
    durationNum: 5,
    price: 290,

    description: "This is the 1 hour Test Package for user",
    features: [
      "Pick up 1 hour before the test.",
      "45 mins warm-up lesson before the test.",
      "Use instructor's car for the test.",
      "Drop-off after the test result is received.",
      "Please call 24 hours prior to the change or cancel your appointment to avoid the full fees penalty.",
      "Only for Disability learner driver.",
    ],

    category: "driving-lesson",
  },
  {
    name: "1 hour lesson",
    packageThumbline: "https://i.ibb.co.com/spdprfQL/1hour-lesson-package.png",
    lessons: 1,
    duration: "1 Hours",
    durationNum: 1,
    price: 75,

    description:
      "The 1 Hour Lesson Package is designed to give learner drivers a focused, supportive session to prepare for their driving test.",
    features: [
      "Automatic Driving Lesson - 7 days a week.  ",
      "Pick up and drop off at your desired location.   ",
      "One-to-one in-vehicle coaching.",
      "Teaching materials are provided.",
      "The test car is available at $220 (includes an hour driving lesson before your driving test).",
      "Please call 24 hours prior to the change or cancel your appointment to avoid the full fees penalty. ",
    ],

    category: "driving-lesson",
  },
  {
    id: 2,
    name: "Standard Package",
    packageImg: packageImg,
    lessons: 10,
    duration: "10 Hours",
    durationNum: 10,
    price: 549,
    originalPrice: 649,
    description: "Build confidence with structured lessons.",
    features: [
      "10 driving lessons",
      "Highway training",
      "Night driving",
      "Free mock test",
    ],
    popular: true,
    savings: 100,
    category: "intermediate",
  },
  {
    id: 3,
    name: "Premium Package",
    packageImg: packageImg,
    lessons: 15,
    duration: "15 Hours",
    durationNum: 15,
    price: 799,
    originalPrice: 949,
    description: "Advanced training with mock test preparation.",
    features: [
      "15 driving lessons",
      "Test routes practice",
      "Priority scheduling",
      "Guaranteed test slot",
    ],
    popular: false,
    savings: 150,
    category: "advanced",
  },
  {
    id: 4,
    name: "Test Ready Package",
    packageImg: packageImg,
    lessons: 3,
    duration: "3 Hours",
    durationNum: 3,
    price: 199,
    originalPrice: 249,
    description: "Final preparation before your driving test.",
    features: [
      "3 intensive lessons",
      "Test simulation",
      "Examiner tips",
      "Car for test day",
    ],
    popular: false,
    savings: 50,
    category: "test",
  },
  {
    id: 5,
    name: "Refresher Package",
    packageImg: packageImg,
    lessons: 4,
    duration: "4 Hours",
    durationNum: 4,
    price: 249,
    originalPrice: 299,
    description: "Ideal for returning or nervous drivers.",
    features: [
      "4 refresher lessons",
      "Confidence building",
      "Road safety update",
      "Flexible timing",
    ],
    popular: false,
    savings: 50,
    category: "refresher",
  },
  {
    id: 6,
    name: "Intensive Course",
    packageImg: packageImg,
    lessons: 20,
    duration: "20 Hours",
    durationNum: 20,
    price: 999,
    originalPrice: 1199,
    description: "Complete driver training in shortest time.",
    features: [
      "20 comprehensive lessons",
      "All road types",
      "Emergency handling",
      "Certificate of completion",
    ],
    popular: true,
    savings: 200,
    category: "intensive",
  },
  {
    id: 7,
    name: "Weekend Warrior",
    packageImg: packageImg,
    lessons: 8,
    duration: "8 Hours",
    durationNum: 8,
    price: 449,
    originalPrice: 529,
    description: "Weekend-only lessons for busy schedules.",
    features: [
      "8 weekend lessons",
      "Saturday/Sunday slots",
      "Pickup service",
      "Progress reports",
    ],
    popular: false,
    savings: 80,
    category: "weekend",
  },
  {
    id: 8,
    name: "Express Pass",
    packageImg: packageImg,
    lessons: 12,
    duration: "12 Hours",
    durationNum: 12,
    price: 699,
    originalPrice: 799,
    description: "Fast-track to your driving test.",
    features: [
      "12 focused lessons",
      "Test booking assistance",
      "Extra practice hours",
      "Discount on retest",
    ],
    popular: true,
    savings: 100,
    category: "fast-track",
  },
];
