export const locations = [
  { name: "Kogarah, NSW", zone: "South" },
  { name: "Rockdale", zone: "South" },
  { name: "Roselands", zone: "South-West" },
  { name: "Sandringham", zone: "South" },
  { name: "Sans Souci", zone: "South" },
  { name: "South Hurstville", zone: "South" },
  { name: "Sutherland", zone: "South" },
  { name: "Sylvania", zone: "South" },
  { name: "Sylvania Waters", zone: "South" },
  { name: "Taren Point", zone: "South" },
  { name: "Tempe", zone: "East" },
  { name: "Turella", zone: "East" },
  { name: "Wali Creek", zone: "East" },
  { name: "Woolooware", zone: "South" },
  { name: "Kirrawee", zone: "South" },
  { name: "Kogarah", zone: "South" },
  { name: "Kogarah Bay", zone: "South" },
  { name: "Kyeemagh", zone: "East" },
  { name: "Marrickville", zone: "Inner-West" },
  { name: "Miranda", zone: "South" },
  { name: "Monterey", zone: "South" },
  { name: "Mortdale", zone: "South-West" },
  { name: "Peakhurst", zone: "South-West" },
  { name: "Penshurst", zone: "South" },
  { name: "Ramsgate", zone: "South" },
  { name: "Ramsgate Beach", zone: "South" },
  { name: "Riverwood", zone: "South-West" },
  { name: "Allawah", zone: "South" },
  { name: "Arncliffe", zone: "South" },
  { name: "Banksia", zone: "South" },
  { name: "Bardwell Park", zone: "Inner-West" },
  { name: "Bardwell Valley", zone: "Inner-West" },
  { name: "Beverly Hills", zone: "South-West" },
  { name: "Bexley", zone: "South" },
  { name: "Bexley North", zone: "South" },
  { name: "Blakehurst", zone: "South" },
  { name: "Botany", zone: "East" },
  { name: "Brighton-Le-Sands", zone: "East" },
  { name: "Caringbah", zone: "South" },
  { name: "Caringbah South", zone: "South" },
  { name: "Carlton", zone: "South" },
  { name: "Carss Park", zone: "South" },
  { name: "Clemton Park", zone: "Inner-West" },
  { name: "Cronulla", zone: "South" },
  { name: "Dolls Point", zone: "South" },
  { name: "Eastgardens", zone: "East" },
  { name: "Endgadline", zone: "East" },
  { name: "Eastlakes", zone: "East" },
  { name: "Gymea", zone: "South" },
  { name: "Gymea Bay", zone: "South" },
  { name: "Hurstville", zone: "South" },
  { name: "Hurstville Grove", zone: "South" },
  { name: "Kangaroo Point", zone: "South" },
  { name: "Kareela", zone: "South" },
  { name: "Kingsgrove", zone: "South-West" },
  { name: "Mascot", zone: "East" },
  { name: "Pagewood", zone: "East" },
  { name: "Port Botany", zone: "East" },
];
