import {Montserrat, Open_Sans} from "next/font/google";
import "./globals.css";
import Header from "./shared/ui/Header";
import Footer from "./shared/ui/Footer";
import TopHeader from "./shared/ui/TopHeader";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "Test Route Driving School",
  description: "Generated by create next app",
};

export default function RootLayout({children}) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} ${openSans.variable} antialiased`}
      >
           <TopHeader />
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
