import {Montserrat, Open_Sans} from "next/font/google";
import "./globals.css";
import Header from "./shared/ui/Header";
import Footer from "./shared/ui/Footer";
import TopHeader from "./shared/ui/TopHeader";
import AuthProvider from "./context/AuthProvider";
import { ToastContainer } from "react-toastify";
import ScrollToTopButton from "./shared/ui/ScrollToTop";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "Test Route Driving School",
  description: "Generated by create next app",
};

export default function RootLayout({children}) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning
        className={`${montserrat.variable} ${openSans.variable} antialiased`}
      >
        <AuthProvider>

          <ToastContainer />
          <TopHeader />
          <Header />
          <main className="min-h-[90vh]">{children}</main>
          <ScrollToTopButton/>
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
