
import "../globals.css";
import {ToastContainer} from "react-toastify";
import TopHeader from "../shared/ui/TopHeader";
import Header from "../shared/ui/Header";
import ScrollToTopButton from "../shared/ui/ScrollToTop";
import Footer from "../shared/ui/Footer";

export const metadata = {
  title: "Test Route Driving School",
  description: "Generated by create next app",
};

export default function BasicLayout({children}) {
  return (
    <div>
     
          <ToastContainer />
          <TopHeader />
          <Header />
          <main className="min-h-[90vh]">{children}</main>
          <div id="recaptcha-container"></div>
          <ScrollToTopButton />

          <Footer />
       
    </div>
  );
}
